site_name: Soleil
site_url: https://docs.soleilshare.com
theme:
  name: material
  custom_dir: overrides
  font: 
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/sun.png
  favicon: assets/sun.ico
  features:
    - navigation.footer
    - navigation.indexes
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Blog:
    - blog/index.md
    - Tags: blog/tags.md
    

plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      pagination_per_page: 10
  - meta
  - tags:
      tags_file: blog/tags.md
  - social:
      cards_layout_options:
            background_color: "#ff1493"
            font_family: "Ma Shan Zheng"
  - rss:
      match_path: "blog/posts/*.md"
      date_from_meta:
        as_creation: data.created
        as_updated: data.updated

hooks:
  - hooks/socialmedia.py

extra:
  social:
    - icon: fontawesome/brands/github
      name: SaintFore
      link: https://github.com/SaintFore
    - icon: simple/csdn
      name: 星空下的惶然
      link: https://blog.csdn.net/soleiltree

copyright: Copyright &copy; 2025 Merlin Soleil