site_name: Soleil
site_url: https://soleil.sbs
theme:
  name: material
  custom_dir: overrides
  font: 
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/sun.png
  favicon: assets/sun.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.instant      # 即时加载页面，无需刷新
    - navigation.tracking     # 在URL中更新当前位置
    - navigation.tabs         # 顶部标签式导航
    - navigation.sections     # 导航分节
    - navigation.expand       # 自动展开导航
    - navigation.top          # 返回顶部按钮
    - toc.follow              # 目录跟随滚动
    - search.suggest          # 搜索建议
    - search.highlight        # 搜索高亮
    - content.code.copy       # 代码块复制按钮
    - content.code.annotate   # 代码注释
    - content.tabs.link       # 标签页链接
    - announce.dismiss        # 公告可关闭
  palette:
  # 深色模式
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    accent: pink
    toggle:
      icon: material/weather-sunny
      name: 切换到浅色模式
  
  # 浅色模式
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: pink
    toggle:
      icon: material/weather-night
      name: 切换到深色模式
  
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:       # 数学公式支持
      generic: true
  - pymdownx.tasklist:         # 任务列表
      custom_checkbox: true
  - pymdownx.critic            # 编辑标记
  - pymdownx.caret             # 上标、下标
  - pymdownx.mark              # 突出显示
  - pymdownx.tilde             # 删除线
  - footnotes                  # 脚注支持
  - abbr                       # 缩写
  - md_in_html                 # HTML中的Markdown

nav:
  - Home: index.md
  - Blog:
    - blog/index.md
    - Tags: blog/tags.md
    

plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      pagination_per_page: 10
  - meta
  - tags:
      tags_file: blog/tags.md
  - glightbox:
      width: 80%
  # - social:
  #     cards_layout_options:
  #           background_color: "#ff1493"
  #           font_family: "Ma Shan Zheng"
  # - rss:
  #     match_path: "blog/posts/*.md"
  #     date_from_meta:
  #       as_creation: data.created
  #       as_updated: data.updated

hooks:
  - hooks/socialmedia.py

extra:
  social:
    - icon: fontawesome/brands/github
      name: SaintFore
      link: https://github.com/SaintFore
    - icon: simple/csdn
      name: 星空下的惶然
      link: https://blog.csdn.net/soleiltree
  annotate:
    json: [.s2]               # 注解JSON字符串
  generator: false            # 移除"Made with Material"

copyright: Copyright &copy; 2025 Merlin Soleil

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/home.css